## Lektüre & Quiz: `S3` 

Lesen Sie das [`S3`](https://adv-r.hadley.nz/s3.html) Kapitel von H. Wickham's *Advanced R*. 
Bearbeiten Sie (mindestens) die folgenden von dort übernommenen/inspirierten Aufgaben:

- Was tut die `as.data.frame.data.frame()` Methode? Warum ist das verwirrend? Wie können Sie derartige Verwirrung in Ihrem eigenen Code vermeiden?
Auf den ersten Blick ist es nicht klar, welcher Punkt den generic von der Klasse trennt: <generic>.<class>()
Punkte bei Benamung vermeiden => snake case benutzen.

- Beschreiben/erklären Sie das Verhalten dieses Codes:
```r
set.seed(1014)
some_days <- as.Date("2019-11-24") + sample(10, 5)
mean(some_days)
# [1] "2019-11-30"
mean(unclass(some_days))
# [1] 18230.4
```
some_days ist ein vector von 5 Dates ab `sample(10, 5)` Tage vom 2019-11-24
mean(some_days) <- "2019-11-30" weil mean(sample(10, 5)) = 6.4 (Tage)
as.POSIXct(mean(some_days)) <- "2019-11-30 10:36:00 CET" weil 0.4 Tage = 9 Std. und 36 min. (+ 1 Std. CET)
mean(unclass(some_days)) <- Anzahl von Tagen vom Unix/Epoch time

- Welche Klasse hat `x` im folgenden Code? Auf welchem *base type* basiert diese Klasse? Welche Attribute nutzt sie und wie sind die mathematischen Eigenschaften von Verteilungsfunktionen hier konkret implementiert? 
```r
x <- ecdf(rpois(100, 10))
x
# Empirical CDF 
# Call: ecdf(rpois(100, 10))
#  x[1:15] =      1,      4,      5,  ...,     16,     17
```
class(x) ergibt die Klasse(n) vom x => "ecdf" "stepfun" "function"
typeof(x) ergibt den Typ => "closure"
attributes(x) ergibt die Attribute => $class und $call

- Schreiben Sie einen neuen low-level Konstruktor für `data.frame`-Objekte (ohne die Funktionen `as.data.frame()` oder `data.frame()` zu benutzen, selbstverständlich). Machen Sie sich zunächst klar: Auf welchem *base type* basiert `data.frame`? Welche Attribute nutzt `data.frame`? Welche Restriktionen gelten für die verschiedenen Einträge und Attribute?  
    *Hinweis*: Sehen Sie sich dafür zunächst mal so etwas wie `str(unclass(<irgend ein data.frame>))` an.
```r
new_data_frame <- function(x = list(), row_names = NULL) {
  
  # validate x
  # at least length of one, unique names and equal lengths of all elements
  checkmate::assert_list(x, min.len = 1)
  col_names <- names(x)
  checkmate::assert_names(col_names, "unique")
  nrows <- length(x[[1]])
  stopifnot(all(lengths(x) == nrows))
  
  # validate row_names
  # same length as nrows and unique
  if (is.null(row_names)) row_names <- as.character(1:nrows)
  checkmate::assert_character(row_names, len = nrows, unique = TRUE)

  structure(x,
    names = col_names,
    row_names = row_names,
    class = "data_frame"
  )
}

new_data_frame(list(a = c(1, 2), b = c(2, 3)))
# duplicate col names
new_data_frame(list(a = c(1, 2), a = c(2, 3)))
# unequal lengths
new_data_frame(list(a = c(1, 2), b = c(2)))
# too few row names
new_data_frame(list(a = c(1, 2), b = c(2, 3)), row_names = "1")
# duplicate row names
new_data_frame(list(a = c(1, 2), b = c(2, 3)), row_names = c("1", "1"))
```
- Kategorisieren Sie die Klassen der Rückgabe-Objekte von `lm(), factor(), table(), as.Date(), as.POSIXct(), ecdf(), ordered(), I()` in die Klassentypen *vector class*, *record style class*, *scalar class* die in *Advanced R* beschrieben  werden.
lm():         scalar
factor():     vector
table():      record
as.Date():    vector
as.POSIXct(): vector
ecdf():       scalar
ordered():    record (same as factor())
I():          all of them?

- Wie sähe ein Konstruktor `new_lm` für Objekte der Klasse `lm` aus? Warum wäre ein solcher Konstruktor vermutlich nicht besonders nützlich? 
- Lesen Sie den Quellcode für `t()` und `t.test()`. Ist `t.test()` eine generische S3 Funktion oder eine S3 Methode? Was passiert im Detail wenn sie `t()` auf ein S3-Objekt mit Klasse `test` anwenden (s.u.)? Warum?
```r
x <- structure(1:10, class = "test")
t(x)
```
`t.test()` ist eine generische S3 Funktion, weil `isS3stdGeneric(t.test)` `TRUE` ergibt.
Außerdem `t.test` zeigt `UseMethod("t.test")`.

```r
# Es wird stats:::t.test.default(x) über method dispatch aufgerufen
x <- structure(1:10, class = "test")
# not a proper test...
checkmate::assert(all(names(t(x)) == names(stats:::t.test.default(x))))
```

